name: jmathDocs

on:
  workflow_run:
    workflows: ["jmathTagger"]
    types:
      - completed

jobs:
  doc-update:

    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install Sphinx 
      run: |
        pip install sphinx 
    - name: Update Docs
      run: |
        sphinx-apidoc -o ./docs/source/ ./jmath --force
    - name: Build and Commit
      uses: sphinx-notes/pages@master
      with:
        documentation_path: ./docs/source/
        extra_files: 'CNAME'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
