name: jmathPublisher

on:
  release:
    types: [published]
    
jobs:
  publish:
  
    name: Publish jmath to PyPi
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Update version.txt
        run: |
          echo ${{steps.get_version.outputs.VERSION}} > "version.txt"
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: version.txt
            commit-msg: Update version to ${{steps.get_version.outputs.VERSION}}
            github-token: ${{secrets.GITHUB_TOKEN}}
      - name: Install Setuptools
        run: |
          python -m pip install setuptools
      - name: Install wheel
        run: |
          python -m pip install wheel
      - name: Build jmath
        run: |
          python setup.py install bdist_wheel
      - name: Publish jmath to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{secrets.PYPI_API_TOKEN}}
