name: jmathPublisher

on:
  release:
    types: [published]
    
jobs:
  publish:
    name: Publish jmath to PyPi
    runs-on: Ubuntu 18.04
    
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Build jmath
        run: |
          python setup.py install bdist_wheel
      - name: Publish jmath to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{secrets.PYPI_API_TOKEN}}
