name: jmathRequirements

on:
  pull_request:
    types: [opened, reopened]

jobs:
  generate_requirements:

    name: Generate requirements.txt
    runs-on: ubuntu-latest

    steps:
       - uses: ryan-rozario/pipreqs-action-cpy@master
       - name: Create requirements.txt

      with:
        PROJECT_PATH: ./
        REQUIREMENT_PATH: ./requirements.txt 