name: jmathRequirements

on:
  pull_request:
    types: [opened, reopened]

jobs:
  generate_requirements:

    name: Generate requirements.txt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Create requirements.txt
        id: add-requirements
        uses: ryan-rozario/pipreqs-action-cpy@master