name: jmathTagger

on:
  workflow_run:
    workflows: ["jmathPublisher"]
    types:
      - completed

jobs:
  tag:
  
    name: Re-tag Repo
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        id: get_version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt
      - name: Echo version
        run: |
          echo "${{steps.package.outputs.content}}"
      - name: Update Tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{steps.package.outputs.content}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}