name: jmathTagger

on:
  workflow_run:
    workflows: ["jmathPublisher"]
    types:
      - completed

jobs:
  tag:
  
    name: Re-tag Repo
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt
      - name: Echo version
        run: |
          echo "${{steps.version.outputs.content}}"
      - name: Update Tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{steps.version.outputs.content}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}